import Head from "next/head";
import { useDropzone, FileWithPath } from "react-dropzone";
import { useMemo } from "react";

const baseStyle = {
  flex: 1,
  display: "flex",
  flexDirection: "column",
  padding: "20px",
  borderWidth: 2,
  borderRadius: 2,
  borderColor: "#eeeeee",
  borderStyle: "dashed",
  backgroundColor: "#fafafa",
  color: "#bdbdbd",
  outline: "none",
  transition: "border .24s ease-in-out",
};

const focusedStyle = {
  borderColor: "#2196f3",
};

const acceptStyle = {
  borderColor: "#00e676",
};

const rejectStyle = {
  borderColor: "#ff1744",
};

export default function Home() {
  const {
    getRootProps,
    getInputProps,
    acceptedFiles,
    isFocused,
    isDragAccept,
    isDragReject,
  } = useDropzone({ accept: { "image/*": [] } });

  const style = useMemo(
    () => ({
      ...baseStyle,
      ...(isFocused ? focusedStyle : {}),
      ...(isDragAccept ? acceptStyle : {}),
      ...(isDragReject ? rejectStyle : {}),
    }),
    [isFocused, isDragAccept, isDragReject]
  );

  const files = acceptedFiles.map((file: FileWithPath) => (
    <li key={file.path}>
      {file.path} - {file.size} bytes
    </li>
  ));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-12 border-zinc-800 border-b pb-6">
        <h1 className="text-5xl">Try for free!</h1>
        <p className="text-zinc-500 pt-2">
          Remove the background from up to 10 images, no charge.
        </p>
      </div>
      <div className="flex mt-12 gap-12">
        <div className="flex-1">
          <h1 className="text-xl mb-4">Upload</h1>
          <div {...getRootProps({ style: style as React.CSSProperties })}>
            <input {...getInputProps()} />
            <p>Drop a image, or click to select one</p>
          </div>
          <ul className="mt-2">{files}</ul>
        </div>
        <div className="flex-1">
          <h1 className="text-xl">Result</h1>
        </div>
      </div>
    </>
  );
}
